# Generated by Django 4.2.3 on 2023-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
